/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertiesIdRouteImport } from './routes/properties.$id'
import { Route as PropertiesIdIndexRouteImport } from './routes/properties.$id.index'
import { Route as PropertiesIdPhotosRouteImport } from './routes/properties.$id.photos'
import { Route as PropertiesIdLaunchRouteImport } from './routes/properties.$id.launch'
import { Route as PropertiesIdChecklistCategoryRouteImport } from './routes/properties.$id.checklist.$category'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/properties/$id',
  path: '/properties/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIdIndexRoute = PropertiesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PropertiesIdRoute,
} as any)
const PropertiesIdPhotosRoute = PropertiesIdPhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => PropertiesIdRoute,
} as any)
const PropertiesIdLaunchRoute = PropertiesIdLaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => PropertiesIdRoute,
} as any)
const PropertiesIdChecklistCategoryRoute =
  PropertiesIdChecklistCategoryRouteImport.update({
    id: '/checklist/$category',
    path: '/checklist/$category',
    getParentRoute: () => PropertiesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/properties/$id': typeof PropertiesIdRouteWithChildren
  '/properties/$id/launch': typeof PropertiesIdLaunchRoute
  '/properties/$id/photos': typeof PropertiesIdPhotosRoute
  '/properties/$id/': typeof PropertiesIdIndexRoute
  '/properties/$id/checklist/$category': typeof PropertiesIdChecklistCategoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/properties/$id/launch': typeof PropertiesIdLaunchRoute
  '/properties/$id/photos': typeof PropertiesIdPhotosRoute
  '/properties/$id': typeof PropertiesIdIndexRoute
  '/properties/$id/checklist/$category': typeof PropertiesIdChecklistCategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/properties/$id': typeof PropertiesIdRouteWithChildren
  '/properties/$id/launch': typeof PropertiesIdLaunchRoute
  '/properties/$id/photos': typeof PropertiesIdPhotosRoute
  '/properties/$id/': typeof PropertiesIdIndexRoute
  '/properties/$id/checklist/$category': typeof PropertiesIdChecklistCategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/properties/$id'
    | '/properties/$id/launch'
    | '/properties/$id/photos'
    | '/properties/$id/'
    | '/properties/$id/checklist/$category'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/properties/$id/launch'
    | '/properties/$id/photos'
    | '/properties/$id'
    | '/properties/$id/checklist/$category'
  id:
    | '__root__'
    | '/'
    | '/properties/$id'
    | '/properties/$id/launch'
    | '/properties/$id/photos'
    | '/properties/$id/'
    | '/properties/$id/checklist/$category'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PropertiesIdRoute: typeof PropertiesIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/properties/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$id/': {
      id: '/properties/$id/'
      path: '/'
      fullPath: '/properties/$id/'
      preLoaderRoute: typeof PropertiesIdIndexRouteImport
      parentRoute: typeof PropertiesIdRoute
    }
    '/properties/$id/photos': {
      id: '/properties/$id/photos'
      path: '/photos'
      fullPath: '/properties/$id/photos'
      preLoaderRoute: typeof PropertiesIdPhotosRouteImport
      parentRoute: typeof PropertiesIdRoute
    }
    '/properties/$id/launch': {
      id: '/properties/$id/launch'
      path: '/launch'
      fullPath: '/properties/$id/launch'
      preLoaderRoute: typeof PropertiesIdLaunchRouteImport
      parentRoute: typeof PropertiesIdRoute
    }
    '/properties/$id/checklist/$category': {
      id: '/properties/$id/checklist/$category'
      path: '/checklist/$category'
      fullPath: '/properties/$id/checklist/$category'
      preLoaderRoute: typeof PropertiesIdChecklistCategoryRouteImport
      parentRoute: typeof PropertiesIdRoute
    }
  }
}

interface PropertiesIdRouteChildren {
  PropertiesIdLaunchRoute: typeof PropertiesIdLaunchRoute
  PropertiesIdPhotosRoute: typeof PropertiesIdPhotosRoute
  PropertiesIdIndexRoute: typeof PropertiesIdIndexRoute
  PropertiesIdChecklistCategoryRoute: typeof PropertiesIdChecklistCategoryRoute
}

const PropertiesIdRouteChildren: PropertiesIdRouteChildren = {
  PropertiesIdLaunchRoute: PropertiesIdLaunchRoute,
  PropertiesIdPhotosRoute: PropertiesIdPhotosRoute,
  PropertiesIdIndexRoute: PropertiesIdIndexRoute,
  PropertiesIdChecklistCategoryRoute: PropertiesIdChecklistCategoryRoute,
}

const PropertiesIdRouteWithChildren = PropertiesIdRoute._addFileChildren(
  PropertiesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PropertiesIdRoute: PropertiesIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
